### imports

In [4]:
import pandas as pd
import os

In [5]:
os.getcwd()

'/content'

### datasets

In [3]:
df = pd.read_csv("data\melb_data.csv")

df2 = pd.read_csv(r"data\toy_dataset.csv")

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
/tmp/ipykernel_9646/3836793875.py:1: SyntaxWarning: invalid escape sequence '\m'
  df = pd.read_csv("data\melb_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data\\melb_data.csv'

### testing

In [ ]:
df2 = df2.reset_index()

df2 = df2.set_index("ID")

df2

     Name  Age  Score       City
ID
1   Aarav   16     85  Bengaluru
2    Diya   17     92     Mysuru
3   Rohan   16     78      Hubli
4   Sneha   18     88  Mangaluru
5   Kiran   17     81   Belagavi

In [ ]:
df2.loc[df2.Age==17]

     Name  Age  Score      City
ID
2    Diya   17     92    Mysuru
5   Kiran   17     81  Belagavi