### imports

In [60]:
import pandas as pd

### datasets

In [ ]:
df = pd.read_csv(r"data\melb_data.csv")

df2 = pd.read_csv(r"data\toy_dataset.csv")

<>:1: SyntaxWarning: invalid escape sequence '\m'
<>:1: SyntaxWarning: invalid escape sequence '\m'
C:\Users\sgoll\AppData\Local\Temp\ipykernel_7584\3836793875.py:1: SyntaxWarning: invalid escape sequence '\m'
  df = pd.read_csv("data\melb_data.csv")

### testing

In [62]:
df2 = df2.reset_index()

df2 = df2.set_index("ID")

df2

    index   Name  Age  Score       City
ID
1       0  Aarav   16     85  Bengaluru
2       1   Diya   17     92     Mysuru
3       2  Rohan   16     78      Hubli
4       3  Sneha   18     88  Mangaluru
5       4  Kiran   17     81   Belagavi

In [63]:
df2.loc[df2.Age==17]

    index   Name  Age  Score      City
ID
2       1   Diya   17     92    Mysuru
5       4  Kiran   17     81  Belagavi